using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace magisterka2.Migrations
{
    /// <inheritdoc />
    public partial class Secondary : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PlayerRanks",
                columns: table => new
                {
                    puuid = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Rank = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlayerRanks", x => x.puuid);
                });

            migrationBuilder.CreateTable(
                name: "Secondary",
                columns: table => new
                {
                    matchId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    puuid = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    rank = table.Column<int>(type: "int", nullable: false),
                    allInPings = table.Column<int>(type: "int", nullable: false),
                    assistMePings = table.Column<int>(type: "int", nullable: false),
                    assists = table.Column<int>(type: "int", nullable: false),
                    baronKills = table.Column<int>(type: "int", nullable: false),
                    bountyLevel = table.Column<int>(type: "int", nullable: false),
                    commandPings = table.Column<int>(type: "int", nullable: false),
                    consumablesPurchased = table.Column<int>(type: "int", nullable: false),
                    damageDealtToBuildings = table.Column<int>(type: "int", nullable: false),
                    damageDealtToObjectives = table.Column<int>(type: "int", nullable: false),
                    damageDealtToTurrets = table.Column<int>(type: "int", nullable: false),
                    damageSelfMitigated = table.Column<int>(type: "int", nullable: false),
                    deaths = table.Column<int>(type: "int", nullable: false),
                    detectorWardsPlaced = table.Column<int>(type: "int", nullable: false),
                    doubleKills = table.Column<int>(type: "int", nullable: false),
                    dragonKills = table.Column<int>(type: "int", nullable: false),
                    eligibleForProgression = table.Column<bool>(type: "bit", nullable: false),
                    enemyMissingPings = table.Column<int>(type: "int", nullable: false),
                    enemyVisionPings = table.Column<int>(type: "int", nullable: false),
                    firstBloodAssist = table.Column<bool>(type: "bit", nullable: false),
                    firstBloodKill = table.Column<bool>(type: "bit", nullable: false),
                    firstTowerAssist = table.Column<bool>(type: "bit", nullable: false),
                    firstTowerKill = table.Column<bool>(type: "bit", nullable: false),
                    gameEndedInEarlySurrender = table.Column<bool>(type: "bit", nullable: false),
                    gameEndedInSurrender = table.Column<bool>(type: "bit", nullable: false),
                    getBackPings = table.Column<int>(type: "int", nullable: false),
                    goldEarned = table.Column<int>(type: "int", nullable: false),
                    goldSpent = table.Column<int>(type: "int", nullable: false),
                    holdPings = table.Column<int>(type: "int", nullable: false),
                    individualPosition = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    inhibitorKills = table.Column<int>(type: "int", nullable: false),
                    inhibitorTakedowns = table.Column<int>(type: "int", nullable: false),
                    inhibitorsLost = table.Column<int>(type: "int", nullable: false),
                    itemsPurchased = table.Column<int>(type: "int", nullable: false),
                    killingSprees = table.Column<int>(type: "int", nullable: false),
                    kills = table.Column<int>(type: "int", nullable: false),
                    lane = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    largestCriticalStrike = table.Column<int>(type: "int", nullable: false),
                    largestKillingSpree = table.Column<int>(type: "int", nullable: false),
                    largestMultiKill = table.Column<int>(type: "int", nullable: false),
                    longestTimeSpentLiving = table.Column<int>(type: "int", nullable: false),
                    magicDamageDealt = table.Column<int>(type: "int", nullable: false),
                    magicDamageDealtToChampions = table.Column<int>(type: "int", nullable: false),
                    magicDamageTaken = table.Column<int>(type: "int", nullable: false),
                    needVisionPings = table.Column<int>(type: "int", nullable: false),
                    neutralMinionsKilled = table.Column<int>(type: "int", nullable: false),
                    nexusKills = table.Column<int>(type: "int", nullable: false),
                    nexusLost = table.Column<int>(type: "int", nullable: false),
                    nexusTakedowns = table.Column<int>(type: "int", nullable: false),
                    objectivesStolen = table.Column<int>(type: "int", nullable: false),
                    objectivesStolenAssists = table.Column<int>(type: "int", nullable: false),
                    onMyWayPings = table.Column<int>(type: "int", nullable: false),
                    pentaKills = table.Column<int>(type: "int", nullable: false),
                    physicalDamageDealt = table.Column<int>(type: "int", nullable: false),
                    physicalDamageDealtToChampions = table.Column<int>(type: "int", nullable: false),
                    physicalDamageTaken = table.Column<int>(type: "int", nullable: false),
                    pushPings = table.Column<int>(type: "int", nullable: false),
                    quadraKills = table.Column<int>(type: "int", nullable: false),
                    retreatPings = table.Column<int>(type: "int", nullable: false),
                    riotIdGameName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    riotIdTagline = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    role = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    spell1Casts = table.Column<int>(type: "int", nullable: false),
                    spell2Casts = table.Column<int>(type: "int", nullable: false),
                    spell3Casts = table.Column<int>(type: "int", nullable: false),
                    spell4Casts = table.Column<int>(type: "int", nullable: false),
                    summoner1Casts = table.Column<int>(type: "int", nullable: false),
                    summoner1Id = table.Column<int>(type: "int", nullable: false),
                    summoner2Casts = table.Column<int>(type: "int", nullable: false),
                    summoner2Id = table.Column<int>(type: "int", nullable: false),
                    summonerId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    summonerLevel = table.Column<int>(type: "int", nullable: false),
                    summonerName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    teamEarlySurrendered = table.Column<bool>(type: "bit", nullable: false),
                    timeCCingOthers = table.Column<int>(type: "int", nullable: false),
                    timePlayed = table.Column<int>(type: "int", nullable: false),
                    totalAllyJungleMinionsKilled = table.Column<int>(type: "int", nullable: false),
                    totalDamageDealt = table.Column<int>(type: "int", nullable: false),
                    totalDamageDealtToChampions = table.Column<int>(type: "int", nullable: false),
                    totalDamageShieldedOnTeammates = table.Column<int>(type: "int", nullable: false),
                    totalDamageTaken = table.Column<int>(type: "int", nullable: false),
                    totalEnemyJungleMinionsKilled = table.Column<int>(type: "int", nullable: false),
                    totalHeal = table.Column<int>(type: "int", nullable: false),
                    totalHealsOnTeammates = table.Column<int>(type: "int", nullable: false),
                    totalMinionsKilled = table.Column<int>(type: "int", nullable: false),
                    totalTimeCCDealt = table.Column<int>(type: "int", nullable: false),
                    totalTimeSpentDead = table.Column<int>(type: "int", nullable: false),
                    totalUnitsHealed = table.Column<int>(type: "int", nullable: false),
                    tripleKills = table.Column<int>(type: "int", nullable: false),
                    trueDamageDealt = table.Column<int>(type: "int", nullable: false),
                    trueDamageDealtToChampions = table.Column<int>(type: "int", nullable: false),
                    trueDamageTaken = table.Column<int>(type: "int", nullable: false),
                    turretKills = table.Column<int>(type: "int", nullable: false),
                    turretTakedowns = table.Column<int>(type: "int", nullable: false),
                    turretsLost = table.Column<int>(type: "int", nullable: false),
                    visionClearedPings = table.Column<int>(type: "int", nullable: false),
                    visionScore = table.Column<int>(type: "int", nullable: false),
                    visionWardsBoughtInGame = table.Column<int>(type: "int", nullable: false),
                    wardsKilled = table.Column<int>(type: "int", nullable: false),
                    wardsPlaced = table.Column<int>(type: "int", nullable: false),
                    win = table.Column<bool>(type: "bit", nullable: false),
                    HealFromMapSources = table.Column<float>(type: "real", nullable: false),
                    InfernalScalePickup = table.Column<int>(type: "int", nullable: false),
                    abilityUses = table.Column<int>(type: "int", nullable: false),
                    alliedJungleMonsterKills = table.Column<int>(type: "int", nullable: false),
                    baronTakedowns = table.Column<int>(type: "int", nullable: false),
                    blastConeOppositeOpponentCount = table.Column<int>(type: "int", nullable: false),
                    bountyGold = table.Column<float>(type: "real", nullable: false),
                    buffsStolen = table.Column<int>(type: "int", nullable: false),
                    controlWardTimeCoverageInRiverOrEnemyHalf = table.Column<float>(type: "real", nullable: false),
                    controlWardsPlaced = table.Column<int>(type: "int", nullable: false),
                    damagePerMinute = table.Column<float>(type: "real", nullable: false),
                    damageTakenOnTeamPercentage = table.Column<float>(type: "real", nullable: false),
                    deathsByEnemyChamps = table.Column<int>(type: "int", nullable: false),
                    dodgeSkillShotsSmallWindow = table.Column<int>(type: "int", nullable: false),
                    dragonTakedowns = table.Column<int>(type: "int", nullable: false),
                    effectiveHealAndShielding = table.Column<float>(type: "real", nullable: false),
                    elderDragonKillsWithOpposingSoul = table.Column<int>(type: "int", nullable: false),
                    elderDragonMultikills = table.Column<int>(type: "int", nullable: false),
                    enemyChampionImmobilizations = table.Column<int>(type: "int", nullable: false),
                    enemyJungleMonsterKills = table.Column<int>(type: "int", nullable: false),
                    epicMonsterKillsNearEnemyJungler = table.Column<int>(type: "int", nullable: false),
                    epicMonsterKillsWithin30SecondsOfSpawn = table.Column<int>(type: "int", nullable: false),
                    epicMonsterSteals = table.Column<int>(type: "int", nullable: false),
                    epicMonsterStolenWithoutSmite = table.Column<int>(type: "int", nullable: false),
                    fullTeamTakedown = table.Column<int>(type: "int", nullable: false),
                    gameLength = table.Column<float>(type: "real", nullable: false),
                    getTakedownsInAllLanesEarlyJungleAsLaner = table.Column<int>(type: "int", nullable: false),
                    goldPerMinute = table.Column<float>(type: "real", nullable: false),
                    immobilizeAndKillWithAlly = table.Column<int>(type: "int", nullable: false),
                    initialBuffCount = table.Column<int>(type: "int", nullable: false),
                    initialCrabCount = table.Column<int>(type: "int", nullable: false),
                    jungleCsBefore10Minutes = table.Column<float>(type: "real", nullable: false),
                    junglerTakedownsNearDamagedEpicMonster = table.Column<int>(type: "int", nullable: false),
                    kTurretsDestroyedBeforePlatesFall = table.Column<int>(type: "int", nullable: false),
                    kda = table.Column<float>(type: "real", nullable: false),
                    killAfterHiddenWithAlly = table.Column<int>(type: "int", nullable: false),
                    killParticipation = table.Column<float>(type: "real", nullable: false),
                    killedChampTookFullTeamDamageSurvived = table.Column<int>(type: "int", nullable: false),
                    killsNearEnemyTurret = table.Column<int>(type: "int", nullable: false),
                    killsOnOtherLanesEarlyJungleAsLaner = table.Column<int>(type: "int", nullable: false),
                    killsUnderOwnTurret = table.Column<int>(type: "int", nullable: false),
                    killsWithHelpFromEpicMonster = table.Column<int>(type: "int", nullable: false),
                    knockEnemyIntoTeamAndKill = table.Column<int>(type: "int", nullable: false),
                    landSkillShotsEarlyGame = table.Column<int>(type: "int", nullable: false),
                    laneMinionsFirst10Minutes = table.Column<int>(type: "int", nullable: false),
                    laningPhaseGoldExpAdvantage = table.Column<int>(type: "int", nullable: false),
                    legendaryCount = table.Column<int>(type: "int", nullable: false),
                    maxCsAdvantageOnLaneOpponent = table.Column<float>(type: "real", nullable: false),
                    maxKillDeficit = table.Column<int>(type: "int", nullable: false),
                    maxLevelLeadLaneOpponent = table.Column<int>(type: "int", nullable: false),
                    moreEnemyJungleThanOpponent = table.Column<float>(type: "real", nullable: false),
                    multiKillOneSpell = table.Column<int>(type: "int", nullable: false),
                    multiTurretRiftHeraldCount = table.Column<int>(type: "int", nullable: false),
                    multikills = table.Column<int>(type: "int", nullable: false),
                    multikillsAfterAggressiveFlash = table.Column<int>(type: "int", nullable: false),
                    outnumberedKills = table.Column<int>(type: "int", nullable: false),
                    outnumberedNexusKill = table.Column<int>(type: "int", nullable: false),
                    perfectDragonSoulsTaken = table.Column<int>(type: "int", nullable: false),
                    perfectGame = table.Column<int>(type: "int", nullable: false),
                    pickKillWithAlly = table.Column<int>(type: "int", nullable: false),
                    quickCleanse = table.Column<int>(type: "int", nullable: false),
                    quickFirstTurret = table.Column<int>(type: "int", nullable: false),
                    quickSoloKills = table.Column<int>(type: "int", nullable: false),
                    riftHeraldTakedowns = table.Column<int>(type: "int", nullable: false),
                    saveAllyFromDeath = table.Column<int>(type: "int", nullable: false),
                    scuttleCrabKills = table.Column<int>(type: "int", nullable: false),
                    skillshotsDodged = table.Column<int>(type: "int", nullable: false),
                    skillshotsHit = table.Column<int>(type: "int", nullable: false),
                    soloBaronKills = table.Column<int>(type: "int", nullable: false),
                    soloKills = table.Column<int>(type: "int", nullable: false),
                    stealthWardsPlaced = table.Column<int>(type: "int", nullable: false),
                    survivedSingleDigitHpCount = table.Column<int>(type: "int", nullable: false),
                    survivedThreeImmobilizesInFight = table.Column<int>(type: "int", nullable: false),
                    takedownOnFirstTurret = table.Column<int>(type: "int", nullable: false),
                    takedowns = table.Column<int>(type: "int", nullable: false),
                    takedownsAfterGainingLevelAdvantage = table.Column<int>(type: "int", nullable: false),
                    takedownsBeforeJungleMinionSpawn = table.Column<int>(type: "int", nullable: false),
                    takedownsFirstXMinutes = table.Column<int>(type: "int", nullable: false),
                    takedownsInAlcove = table.Column<int>(type: "int", nullable: false),
                    takedownsInEnemyFountain = table.Column<int>(type: "int", nullable: false),
                    teamBaronKills = table.Column<int>(type: "int", nullable: false),
                    teamDamagePercentage = table.Column<float>(type: "real", nullable: false),
                    teamElderDragonKills = table.Column<int>(type: "int", nullable: false),
                    teamRiftHeraldKills = table.Column<int>(type: "int", nullable: false),
                    tookLargeDamageSurvived = table.Column<int>(type: "int", nullable: false),
                    turretPlatesTaken = table.Column<int>(type: "int", nullable: false),
                    turretsTakenWithRiftHerald = table.Column<int>(type: "int", nullable: false),
                    twentyMinionsIn3SecondsCount = table.Column<int>(type: "int", nullable: false),
                    twoWardsOneSweeperCount = table.Column<int>(type: "int", nullable: false),
                    visionScoreAdvantageLaneOpponent = table.Column<float>(type: "real", nullable: false),
                    visionScorePerMinute = table.Column<float>(type: "real", nullable: false),
                    voidMonsterKill = table.Column<int>(type: "int", nullable: false),
                    wardTakedowns = table.Column<int>(type: "int", nullable: false),
                    wardTakedownsBefore20M = table.Column<int>(type: "int", nullable: false),
                    wardsGuarded = table.Column<int>(type: "int", nullable: false),
                    earliestDragonTakedown = table.Column<float>(type: "real", nullable: false),
                    junglerKillsEarlyJungle = table.Column<int>(type: "int", nullable: false),
                    killsOnLanersEarlyJungleAsJungler = table.Column<int>(type: "int", nullable: false),
                    baronBuffGoldAdvantageOverThreshold = table.Column<int>(type: "int", nullable: false),
                    earliestBaron = table.Column<float>(type: "real", nullable: false),
                    firstTurretKilledTime = table.Column<float>(type: "real", nullable: false),
                    highestChampionDamage = table.Column<int>(type: "int", nullable: false),
                    soloTurretsLategame = table.Column<int>(type: "int", nullable: false),
                    fasterSupportQuestCompletion = table.Column<int>(type: "int", nullable: false),
                    highestCrowdControlScore = table.Column<int>(type: "int", nullable: false),
                    atakhan = table.Column<int>(type: "int", nullable: false),
                    atakhan_first = table.Column<bool>(type: "bit", nullable: false),
                    baron = table.Column<int>(type: "int", nullable: false),
                    baron_first = table.Column<bool>(type: "bit", nullable: false),
                    champion = table.Column<int>(type: "int", nullable: false),
                    champion_first = table.Column<bool>(type: "bit", nullable: false),
                    dragon = table.Column<int>(type: "int", nullable: false),
                    dragon_first = table.Column<bool>(type: "bit", nullable: false),
                    horde = table.Column<int>(type: "int", nullable: false),
                    horde_first = table.Column<bool>(type: "bit", nullable: false),
                    inhibitor = table.Column<int>(type: "int", nullable: false),
                    inhibitor_first = table.Column<bool>(type: "bit", nullable: false),
                    riftHerald = table.Column<int>(type: "int", nullable: false),
                    riftHerald_first = table.Column<bool>(type: "bit", nullable: false),
                    tower = table.Column<int>(type: "int", nullable: false),
                    tower_first = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Secondary", x => new { x.matchId, x.puuid });
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PlayerRanks");

            migrationBuilder.DropTable(
                name: "Secondary");
        }
    }
}
