// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using magisterka2;

#nullable disable

namespace magisterka2.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251015142924_secondary-awerage2")]
    partial class secondaryawerage2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("magisterka2.PlayerRank", b =>
                {
                    b.Property<string>("puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("riotIdGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("puuid");

                    b.ToTable("PlayerRanks");
                });

            modelBuilder.Entity("magisterka2.Primary", b =>
                {
                    b.Property<string>("matchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("participantId")
                        .HasColumnType("int");

                    b.Property<float>("HealFromMapSources")
                        .HasColumnType("real");

                    b.Property<int>("InfernalScalePickup")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore0")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore1")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore10")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore11")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore2")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore3")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore4")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore5")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore6")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore7")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore8")
                        .HasColumnType("int");

                    b.Property<int>("PlayerScore9")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_DefeatAatrox")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_DefeatBriar")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_DefeatMiniBosses")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_EvolveWeapon")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_Have3Passives")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_KillEnemy")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_PickupGold")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_ReachLevel50")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_Survive15Min")
                        .HasColumnType("int");

                    b.Property<int>("SWARM_WinWith5EvolvedWeapons")
                        .HasColumnType("int");

                    b.Property<int>("_12AssistStreakCount")
                        .HasColumnType("int");

                    b.Property<int>("abilityUses")
                        .HasColumnType("int");

                    b.Property<int>("acesBefore15Minutes")
                        .HasColumnType("int");

                    b.Property<int>("allInPings")
                        .HasColumnType("int");

                    b.Property<int>("alliedJungleMonsterKills")
                        .HasColumnType("int");

                    b.Property<int>("assistMePings")
                        .HasColumnType("int");

                    b.Property<int>("assists")
                        .HasColumnType("int");

                    b.Property<int>("atakhan")
                        .HasColumnType("int");

                    b.Property<bool>("atakhan_first")
                        .HasColumnType("bit");

                    b.Property<int>("baron")
                        .HasColumnType("int");

                    b.Property<int>("baronBuffGoldAdvantageOverThreshold")
                        .HasColumnType("int");

                    b.Property<int>("baronKills")
                        .HasColumnType("int");

                    b.Property<int>("baronTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("baron_first")
                        .HasColumnType("bit");

                    b.Property<int>("basicPings")
                        .HasColumnType("int");

                    b.Property<int>("blastConeOppositeOpponentCount")
                        .HasColumnType("int");

                    b.Property<float>("bountyGold")
                        .HasColumnType("real");

                    b.Property<int>("bountyLevel")
                        .HasColumnType("int");

                    b.Property<int>("buffsStolen")
                        .HasColumnType("int");

                    b.Property<int>("champExperience")
                        .HasColumnType("int");

                    b.Property<int>("champLevel")
                        .HasColumnType("int");

                    b.Property<int>("champion")
                        .HasColumnType("int");

                    b.Property<int>("championId")
                        .HasColumnType("int");

                    b.Property<string>("championName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("championTransform")
                        .HasColumnType("int");

                    b.Property<bool>("champion_first")
                        .HasColumnType("bit");

                    b.Property<int>("commandPings")
                        .HasColumnType("int");

                    b.Property<int>("completeSupportQuestInTime")
                        .HasColumnType("int");

                    b.Property<int>("consumablesPurchased")
                        .HasColumnType("int");

                    b.Property<float>("controlWardTimeCoverageInRiverOrEnemyHalf")
                        .HasColumnType("real");

                    b.Property<int>("controlWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToBuildings")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToObjectives")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToTurrets")
                        .HasColumnType("int");

                    b.Property<float>("damagePerMinute")
                        .HasColumnType("real");

                    b.Property<int>("damageSelfMitigated")
                        .HasColumnType("int");

                    b.Property<float>("damageTakenOnTeamPercentage")
                        .HasColumnType("real");

                    b.Property<int>("dancedWithRiftHerald")
                        .HasColumnType("int");

                    b.Property<int>("dangerPings")
                        .HasColumnType("int");

                    b.Property<int>("deaths")
                        .HasColumnType("int");

                    b.Property<int>("deathsByEnemyChamps")
                        .HasColumnType("int");

                    b.Property<int>("detectorWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("dodgeSkillShotsSmallWindow")
                        .HasColumnType("int");

                    b.Property<int>("doubleAces")
                        .HasColumnType("int");

                    b.Property<int>("doubleKills")
                        .HasColumnType("int");

                    b.Property<int>("dragon")
                        .HasColumnType("int");

                    b.Property<int>("dragonKills")
                        .HasColumnType("int");

                    b.Property<int>("dragonTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("dragon_first")
                        .HasColumnType("bit");

                    b.Property<float>("earliestBaron")
                        .HasColumnType("real");

                    b.Property<float>("earliestDragonTakedown")
                        .HasColumnType("real");

                    b.Property<int>("earlyLaningPhaseGoldExpAdvantage")
                        .HasColumnType("int");

                    b.Property<float>("effectiveHealAndShielding")
                        .HasColumnType("real");

                    b.Property<int>("elderDragonKillsWithOpposingSoul")
                        .HasColumnType("int");

                    b.Property<int>("elderDragonMultikills")
                        .HasColumnType("int");

                    b.Property<bool>("eligibleForProgression")
                        .HasColumnType("bit");

                    b.Property<int>("enemyChampionImmobilizations")
                        .HasColumnType("int");

                    b.Property<int>("enemyJungleMonsterKills")
                        .HasColumnType("int");

                    b.Property<int>("enemyMissingPings")
                        .HasColumnType("int");

                    b.Property<int>("enemyVisionPings")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterKillsNearEnemyJungler")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterKillsWithin30SecondsOfSpawn")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterSteals")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterStolenWithoutSmite")
                        .HasColumnType("int");

                    b.Property<int>("fasterSupportQuestCompletion")
                        .HasColumnType("int");

                    b.Property<bool>("firstBloodAssist")
                        .HasColumnType("bit");

                    b.Property<bool>("firstBloodKill")
                        .HasColumnType("bit");

                    b.Property<bool>("firstTowerAssist")
                        .HasColumnType("bit");

                    b.Property<bool>("firstTowerKill")
                        .HasColumnType("bit");

                    b.Property<int>("firstTurretKilled")
                        .HasColumnType("int");

                    b.Property<float>("firstTurretKilledTime")
                        .HasColumnType("real");

                    b.Property<int>("fistBumpParticipation")
                        .HasColumnType("int");

                    b.Property<int>("flawlessAces")
                        .HasColumnType("int");

                    b.Property<int>("fullTeamTakedown")
                        .HasColumnType("int");

                    b.Property<bool>("gameEndedInEarlySurrender")
                        .HasColumnType("bit");

                    b.Property<bool>("gameEndedInSurrender")
                        .HasColumnType("bit");

                    b.Property<float>("gameLength")
                        .HasColumnType("real");

                    b.Property<int>("getBackPings")
                        .HasColumnType("int");

                    b.Property<int>("getTakedownsInAllLanesEarlyJungleAsLaner")
                        .HasColumnType("int");

                    b.Property<int>("goldEarned")
                        .HasColumnType("int");

                    b.Property<float>("goldPerMinute")
                        .HasColumnType("real");

                    b.Property<int>("goldSpent")
                        .HasColumnType("int");

                    b.Property<int>("hadOpenNexus")
                        .HasColumnType("int");

                    b.Property<int>("highestChampionDamage")
                        .HasColumnType("int");

                    b.Property<int>("highestCrowdControlScore")
                        .HasColumnType("int");

                    b.Property<int>("highestWardKills")
                        .HasColumnType("int");

                    b.Property<int>("holdPings")
                        .HasColumnType("int");

                    b.Property<int>("horde")
                        .HasColumnType("int");

                    b.Property<bool>("horde_first")
                        .HasColumnType("bit");

                    b.Property<int>("immobilizeAndKillWithAlly")
                        .HasColumnType("int");

                    b.Property<string>("individualPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inhibitor")
                        .HasColumnType("int");

                    b.Property<int>("inhibitorKills")
                        .HasColumnType("int");

                    b.Property<int>("inhibitorTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("inhibitor_first")
                        .HasColumnType("bit");

                    b.Property<int>("inhibitorsLost")
                        .HasColumnType("int");

                    b.Property<int>("initialBuffCount")
                        .HasColumnType("int");

                    b.Property<int>("initialCrabCount")
                        .HasColumnType("int");

                    b.Property<int>("item0")
                        .HasColumnType("int");

                    b.Property<int>("item1")
                        .HasColumnType("int");

                    b.Property<int>("item2")
                        .HasColumnType("int");

                    b.Property<int>("item3")
                        .HasColumnType("int");

                    b.Property<int>("item4")
                        .HasColumnType("int");

                    b.Property<int>("item5")
                        .HasColumnType("int");

                    b.Property<int>("item6")
                        .HasColumnType("int");

                    b.Property<int>("itemsPurchased")
                        .HasColumnType("int");

                    b.Property<float>("jungleCsBefore10Minutes")
                        .HasColumnType("real");

                    b.Property<int>("junglerKillsEarlyJungle")
                        .HasColumnType("int");

                    b.Property<int>("junglerTakedownsNearDamagedEpicMonster")
                        .HasColumnType("int");

                    b.Property<int>("kTurretsDestroyedBeforePlatesFall")
                        .HasColumnType("int");

                    b.Property<float>("kda")
                        .HasColumnType("real");

                    b.Property<int>("killAfterHiddenWithAlly")
                        .HasColumnType("int");

                    b.Property<float>("killParticipation")
                        .HasColumnType("real");

                    b.Property<int>("killedChampTookFullTeamDamageSurvived")
                        .HasColumnType("int");

                    b.Property<int>("killingSprees")
                        .HasColumnType("int");

                    b.Property<int>("killingSprees_Chellenges")
                        .HasColumnType("int");

                    b.Property<int>("kills")
                        .HasColumnType("int");

                    b.Property<int>("killsNearEnemyTurret")
                        .HasColumnType("int");

                    b.Property<int>("killsOnLanersEarlyJungleAsJungler")
                        .HasColumnType("int");

                    b.Property<int>("killsOnOtherLanesEarlyJungleAsLaner")
                        .HasColumnType("int");

                    b.Property<int>("killsOnRecentlyHealedByAramPack")
                        .HasColumnType("int");

                    b.Property<int>("killsUnderOwnTurret")
                        .HasColumnType("int");

                    b.Property<int>("killsWithHelpFromEpicMonster")
                        .HasColumnType("int");

                    b.Property<int>("knockEnemyIntoTeamAndKill")
                        .HasColumnType("int");

                    b.Property<int>("landSkillShotsEarlyGame")
                        .HasColumnType("int");

                    b.Property<string>("lane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("laneMinionsFirst10Minutes")
                        .HasColumnType("int");

                    b.Property<int>("laningPhaseGoldExpAdvantage")
                        .HasColumnType("int");

                    b.Property<int>("largestCriticalStrike")
                        .HasColumnType("int");

                    b.Property<int>("largestKillingSpree")
                        .HasColumnType("int");

                    b.Property<int>("largestMultiKill")
                        .HasColumnType("int");

                    b.Property<int>("legendaryCount")
                        .HasColumnType("int");

                    b.Property<int>("longestTimeSpentLiving")
                        .HasColumnType("int");

                    b.Property<int>("lostAnInhibitor")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageTaken")
                        .HasColumnType("int");

                    b.Property<float>("maxCsAdvantageOnLaneOpponent")
                        .HasColumnType("real");

                    b.Property<int>("maxKillDeficit")
                        .HasColumnType("int");

                    b.Property<int>("maxLevelLeadLaneOpponent")
                        .HasColumnType("int");

                    b.Property<int>("mejaisFullStackInTime")
                        .HasColumnType("int");

                    b.Property<float>("moreEnemyJungleThanOpponent")
                        .HasColumnType("real");

                    b.Property<int>("multiKillOneSpell")
                        .HasColumnType("int");

                    b.Property<int>("multiTurretRiftHeraldCount")
                        .HasColumnType("int");

                    b.Property<int>("multikills")
                        .HasColumnType("int");

                    b.Property<int>("multikillsAfterAggressiveFlash")
                        .HasColumnType("int");

                    b.Property<int>("needVisionPings")
                        .HasColumnType("int");

                    b.Property<int>("neutralMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("nexusKills")
                        .HasColumnType("int");

                    b.Property<int>("nexusLost")
                        .HasColumnType("int");

                    b.Property<int>("nexusTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("objectivesStolen")
                        .HasColumnType("int");

                    b.Property<int>("objectivesStolenAssists")
                        .HasColumnType("int");

                    b.Property<int>("onMyWayPings")
                        .HasColumnType("int");

                    b.Property<int>("outerTurretExecutesBefore10Minutes")
                        .HasColumnType("int");

                    b.Property<int>("outnumberedKills")
                        .HasColumnType("int");

                    b.Property<int>("outnumberedNexusKill")
                        .HasColumnType("int");

                    b.Property<int>("pentaKills")
                        .HasColumnType("int");

                    b.Property<int>("perfectDragonSoulsTaken")
                        .HasColumnType("int");

                    b.Property<int>("perfectGame")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("pickKillWithAlly")
                        .HasColumnType("int");

                    b.Property<int>("placement")
                        .HasColumnType("int");

                    b.Property<int>("playedChampSelectPosition")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment1")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment2")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment3")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment4")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment5")
                        .HasColumnType("int");

                    b.Property<int>("playerAugment6")
                        .HasColumnType("int");

                    b.Property<int>("playerSubteamId")
                        .HasColumnType("int");

                    b.Property<int>("poroExplosions")
                        .HasColumnType("int");

                    b.Property<int>("profileIcon")
                        .HasColumnType("int");

                    b.Property<int>("pushPings")
                        .HasColumnType("int");

                    b.Property<string>("puuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quadraKills")
                        .HasColumnType("int");

                    b.Property<int>("quickCleanse")
                        .HasColumnType("int");

                    b.Property<int>("quickFirstTurret")
                        .HasColumnType("int");

                    b.Property<int>("quickSoloKills")
                        .HasColumnType("int");

                    b.Property<int>("retreatPings")
                        .HasColumnType("int");

                    b.Property<int>("riftHerald")
                        .HasColumnType("int");

                    b.Property<int>("riftHeraldTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("riftHerald_first")
                        .HasColumnType("bit");

                    b.Property<string>("riotIdGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("saveAllyFromDeath")
                        .HasColumnType("int");

                    b.Property<int>("scuttleCrabKills")
                        .HasColumnType("int");

                    b.Property<int>("sightWardsBoughtInGame")
                        .HasColumnType("int");

                    b.Property<int>("skillshotsDodged")
                        .HasColumnType("int");

                    b.Property<int>("skillshotsHit")
                        .HasColumnType("int");

                    b.Property<int>("snowballsHit")
                        .HasColumnType("int");

                    b.Property<int>("soloBaronKills")
                        .HasColumnType("int");

                    b.Property<int>("soloKills")
                        .HasColumnType("int");

                    b.Property<int>("soloTurretsLategame")
                        .HasColumnType("int");

                    b.Property<int>("spell1Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell2Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell3Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell4Casts")
                        .HasColumnType("int");

                    b.Property<int>("stealthWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("subteamPlacement")
                        .HasColumnType("int");

                    b.Property<int>("summoner1Casts")
                        .HasColumnType("int");

                    b.Property<int>("summoner1Id")
                        .HasColumnType("int");

                    b.Property<int>("summoner2Casts")
                        .HasColumnType("int");

                    b.Property<int>("summoner2Id")
                        .HasColumnType("int");

                    b.Property<string>("summonerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("summonerLevel")
                        .HasColumnType("int");

                    b.Property<string>("summonerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("survivedSingleDigitHpCount")
                        .HasColumnType("int");

                    b.Property<int>("survivedThreeImmobilizesInFight")
                        .HasColumnType("int");

                    b.Property<int>("takedownOnFirstTurret")
                        .HasColumnType("int");

                    b.Property<int>("takedowns")
                        .HasColumnType("int");

                    b.Property<int>("takedownsAfterGainingLevelAdvantage")
                        .HasColumnType("int");

                    b.Property<int>("takedownsBeforeJungleMinionSpawn")
                        .HasColumnType("int");

                    b.Property<int>("takedownsFirstXMinutes")
                        .HasColumnType("int");

                    b.Property<int>("takedownsInAlcove")
                        .HasColumnType("int");

                    b.Property<int>("takedownsInEnemyFountain")
                        .HasColumnType("int");

                    b.Property<int>("teamBaronKills")
                        .HasColumnType("int");

                    b.Property<float>("teamDamagePercentage")
                        .HasColumnType("real");

                    b.Property<bool>("teamEarlySurrendered")
                        .HasColumnType("bit");

                    b.Property<int>("teamElderDragonKills")
                        .HasColumnType("int");

                    b.Property<int>("teamId")
                        .HasColumnType("int");

                    b.Property<string>("teamPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teamRiftHeraldKills")
                        .HasColumnType("int");

                    b.Property<int>("timeCCingOthers")
                        .HasColumnType("int");

                    b.Property<int>("timePlayed")
                        .HasColumnType("int");

                    b.Property<int>("tookLargeDamageSurvived")
                        .HasColumnType("int");

                    b.Property<int>("totalAllyJungleMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageShieldedOnTeammates")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("totalEnemyJungleMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalHeal")
                        .HasColumnType("int");

                    b.Property<int>("totalHealsOnTeammates")
                        .HasColumnType("int");

                    b.Property<int>("totalMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalTimeCCDealt")
                        .HasColumnType("int");

                    b.Property<int>("totalTimeSpentDead")
                        .HasColumnType("int");

                    b.Property<int>("totalUnitsHealed")
                        .HasColumnType("int");

                    b.Property<int>("tower")
                        .HasColumnType("int");

                    b.Property<bool>("tower_first")
                        .HasColumnType("bit");

                    b.Property<int>("tripleKills")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("turretKills")
                        .HasColumnType("int");

                    b.Property<int>("turretPlatesTaken")
                        .HasColumnType("int");

                    b.Property<int>("turretTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("turretTakedowns_Chellenges")
                        .HasColumnType("int");

                    b.Property<int>("turretsLost")
                        .HasColumnType("int");

                    b.Property<int>("turretsTakenWithRiftHerald")
                        .HasColumnType("int");

                    b.Property<int>("twentyMinionsIn3SecondsCount")
                        .HasColumnType("int");

                    b.Property<int>("twoWardsOneSweeperCount")
                        .HasColumnType("int");

                    b.Property<int>("unrealKills")
                        .HasColumnType("int");

                    b.Property<int>("unseenRecalls")
                        .HasColumnType("int");

                    b.Property<int>("visionClearedPings")
                        .HasColumnType("int");

                    b.Property<int>("visionScore")
                        .HasColumnType("int");

                    b.Property<float>("visionScoreAdvantageLaneOpponent")
                        .HasColumnType("real");

                    b.Property<float>("visionScorePerMinute")
                        .HasColumnType("real");

                    b.Property<int>("visionWardsBoughtInGame")
                        .HasColumnType("int");

                    b.Property<int>("voidMonsterKill")
                        .HasColumnType("int");

                    b.Property<int>("wardTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("wardTakedownsBefore20M")
                        .HasColumnType("int");

                    b.Property<int>("wardsGuarded")
                        .HasColumnType("int");

                    b.Property<int>("wardsKilled")
                        .HasColumnType("int");

                    b.Property<int>("wardsPlaced")
                        .HasColumnType("int");

                    b.Property<bool>("win")
                        .HasColumnType("bit");

                    b.HasKey("matchId", "participantId");

                    b.ToTable("Primary");
                });

            modelBuilder.Entity("magisterka2.Secondary", b =>
                {
                    b.Property<string>("matchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("HealFromMapSources")
                        .HasColumnType("real");

                    b.Property<int>("InfernalScalePickup")
                        .HasColumnType("int");

                    b.Property<int>("abilityUses")
                        .HasColumnType("int");

                    b.Property<int>("allInPings")
                        .HasColumnType("int");

                    b.Property<int>("alliedJungleMonsterKills")
                        .HasColumnType("int");

                    b.Property<int>("assistMePings")
                        .HasColumnType("int");

                    b.Property<int>("assists")
                        .HasColumnType("int");

                    b.Property<int>("atakhan")
                        .HasColumnType("int");

                    b.Property<bool>("atakhan_first")
                        .HasColumnType("bit");

                    b.Property<int>("baron")
                        .HasColumnType("int");

                    b.Property<int>("baronBuffGoldAdvantageOverThreshold")
                        .HasColumnType("int");

                    b.Property<int>("baronKills")
                        .HasColumnType("int");

                    b.Property<int>("baronTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("baron_first")
                        .HasColumnType("bit");

                    b.Property<int>("blastConeOppositeOpponentCount")
                        .HasColumnType("int");

                    b.Property<float>("bountyGold")
                        .HasColumnType("real");

                    b.Property<int>("bountyLevel")
                        .HasColumnType("int");

                    b.Property<int>("buffsStolen")
                        .HasColumnType("int");

                    b.Property<int>("champion")
                        .HasColumnType("int");

                    b.Property<bool>("champion_first")
                        .HasColumnType("bit");

                    b.Property<int>("commandPings")
                        .HasColumnType("int");

                    b.Property<int>("consumablesPurchased")
                        .HasColumnType("int");

                    b.Property<float>("controlWardTimeCoverageInRiverOrEnemyHalf")
                        .HasColumnType("real");

                    b.Property<int>("controlWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToBuildings")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToObjectives")
                        .HasColumnType("int");

                    b.Property<int>("damageDealtToTurrets")
                        .HasColumnType("int");

                    b.Property<float>("damagePerMinute")
                        .HasColumnType("real");

                    b.Property<int>("damageSelfMitigated")
                        .HasColumnType("int");

                    b.Property<float>("damageTakenOnTeamPercentage")
                        .HasColumnType("real");

                    b.Property<int>("deaths")
                        .HasColumnType("int");

                    b.Property<int>("deathsByEnemyChamps")
                        .HasColumnType("int");

                    b.Property<int>("detectorWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("dodgeSkillShotsSmallWindow")
                        .HasColumnType("int");

                    b.Property<int>("doubleKills")
                        .HasColumnType("int");

                    b.Property<int>("dragon")
                        .HasColumnType("int");

                    b.Property<int>("dragonKills")
                        .HasColumnType("int");

                    b.Property<int>("dragonTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("dragon_first")
                        .HasColumnType("bit");

                    b.Property<float>("earliestBaron")
                        .HasColumnType("real");

                    b.Property<float>("earliestDragonTakedown")
                        .HasColumnType("real");

                    b.Property<float>("effectiveHealAndShielding")
                        .HasColumnType("real");

                    b.Property<int>("elderDragonKillsWithOpposingSoul")
                        .HasColumnType("int");

                    b.Property<int>("elderDragonMultikills")
                        .HasColumnType("int");

                    b.Property<bool>("eligibleForProgression")
                        .HasColumnType("bit");

                    b.Property<int>("enemyChampionImmobilizations")
                        .HasColumnType("int");

                    b.Property<int>("enemyJungleMonsterKills")
                        .HasColumnType("int");

                    b.Property<int>("enemyMissingPings")
                        .HasColumnType("int");

                    b.Property<int>("enemyVisionPings")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterKillsNearEnemyJungler")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterKillsWithin30SecondsOfSpawn")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterSteals")
                        .HasColumnType("int");

                    b.Property<int>("epicMonsterStolenWithoutSmite")
                        .HasColumnType("int");

                    b.Property<int>("fasterSupportQuestCompletion")
                        .HasColumnType("int");

                    b.Property<bool>("firstBloodAssist")
                        .HasColumnType("bit");

                    b.Property<bool>("firstBloodKill")
                        .HasColumnType("bit");

                    b.Property<bool>("firstTowerAssist")
                        .HasColumnType("bit");

                    b.Property<bool>("firstTowerKill")
                        .HasColumnType("bit");

                    b.Property<float>("firstTurretKilledTime")
                        .HasColumnType("real");

                    b.Property<int>("fullTeamTakedown")
                        .HasColumnType("int");

                    b.Property<bool>("gameEndedInEarlySurrender")
                        .HasColumnType("bit");

                    b.Property<bool>("gameEndedInSurrender")
                        .HasColumnType("bit");

                    b.Property<float>("gameLength")
                        .HasColumnType("real");

                    b.Property<int>("getBackPings")
                        .HasColumnType("int");

                    b.Property<int>("getTakedownsInAllLanesEarlyJungleAsLaner")
                        .HasColumnType("int");

                    b.Property<int>("goldEarned")
                        .HasColumnType("int");

                    b.Property<float>("goldPerMinute")
                        .HasColumnType("real");

                    b.Property<int>("goldSpent")
                        .HasColumnType("int");

                    b.Property<int>("highestChampionDamage")
                        .HasColumnType("int");

                    b.Property<int>("highestCrowdControlScore")
                        .HasColumnType("int");

                    b.Property<int>("holdPings")
                        .HasColumnType("int");

                    b.Property<int>("horde")
                        .HasColumnType("int");

                    b.Property<bool>("horde_first")
                        .HasColumnType("bit");

                    b.Property<int>("immobilizeAndKillWithAlly")
                        .HasColumnType("int");

                    b.Property<string>("individualPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inhibitor")
                        .HasColumnType("int");

                    b.Property<int>("inhibitorKills")
                        .HasColumnType("int");

                    b.Property<int>("inhibitorTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("inhibitor_first")
                        .HasColumnType("bit");

                    b.Property<int>("inhibitorsLost")
                        .HasColumnType("int");

                    b.Property<int>("initialBuffCount")
                        .HasColumnType("int");

                    b.Property<int>("initialCrabCount")
                        .HasColumnType("int");

                    b.Property<int>("itemsPurchased")
                        .HasColumnType("int");

                    b.Property<float>("jungleCsBefore10Minutes")
                        .HasColumnType("real");

                    b.Property<int>("junglerKillsEarlyJungle")
                        .HasColumnType("int");

                    b.Property<int>("junglerTakedownsNearDamagedEpicMonster")
                        .HasColumnType("int");

                    b.Property<int>("kTurretsDestroyedBeforePlatesFall")
                        .HasColumnType("int");

                    b.Property<float>("kda")
                        .HasColumnType("real");

                    b.Property<int>("killAfterHiddenWithAlly")
                        .HasColumnType("int");

                    b.Property<float>("killParticipation")
                        .HasColumnType("real");

                    b.Property<int>("killedChampTookFullTeamDamageSurvived")
                        .HasColumnType("int");

                    b.Property<int>("killingSprees")
                        .HasColumnType("int");

                    b.Property<int>("kills")
                        .HasColumnType("int");

                    b.Property<int>("killsNearEnemyTurret")
                        .HasColumnType("int");

                    b.Property<int>("killsOnLanersEarlyJungleAsJungler")
                        .HasColumnType("int");

                    b.Property<int>("killsOnOtherLanesEarlyJungleAsLaner")
                        .HasColumnType("int");

                    b.Property<int>("killsUnderOwnTurret")
                        .HasColumnType("int");

                    b.Property<int>("killsWithHelpFromEpicMonster")
                        .HasColumnType("int");

                    b.Property<int>("knockEnemyIntoTeamAndKill")
                        .HasColumnType("int");

                    b.Property<int>("landSkillShotsEarlyGame")
                        .HasColumnType("int");

                    b.Property<string>("lane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("laneMinionsFirst10Minutes")
                        .HasColumnType("int");

                    b.Property<int>("laningPhaseGoldExpAdvantage")
                        .HasColumnType("int");

                    b.Property<int>("largestCriticalStrike")
                        .HasColumnType("int");

                    b.Property<int>("largestKillingSpree")
                        .HasColumnType("int");

                    b.Property<int>("largestMultiKill")
                        .HasColumnType("int");

                    b.Property<int>("legendaryCount")
                        .HasColumnType("int");

                    b.Property<int>("longestTimeSpentLiving")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("magicDamageTaken")
                        .HasColumnType("int");

                    b.Property<float>("maxCsAdvantageOnLaneOpponent")
                        .HasColumnType("real");

                    b.Property<int>("maxKillDeficit")
                        .HasColumnType("int");

                    b.Property<int>("maxLevelLeadLaneOpponent")
                        .HasColumnType("int");

                    b.Property<float>("moreEnemyJungleThanOpponent")
                        .HasColumnType("real");

                    b.Property<int>("multiKillOneSpell")
                        .HasColumnType("int");

                    b.Property<int>("multiTurretRiftHeraldCount")
                        .HasColumnType("int");

                    b.Property<int>("multikills")
                        .HasColumnType("int");

                    b.Property<int>("multikillsAfterAggressiveFlash")
                        .HasColumnType("int");

                    b.Property<int>("needVisionPings")
                        .HasColumnType("int");

                    b.Property<int>("neutralMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("nexusKills")
                        .HasColumnType("int");

                    b.Property<int>("nexusLost")
                        .HasColumnType("int");

                    b.Property<int>("nexusTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("objectivesStolen")
                        .HasColumnType("int");

                    b.Property<int>("objectivesStolenAssists")
                        .HasColumnType("int");

                    b.Property<int>("onMyWayPings")
                        .HasColumnType("int");

                    b.Property<int>("outnumberedKills")
                        .HasColumnType("int");

                    b.Property<int>("outnumberedNexusKill")
                        .HasColumnType("int");

                    b.Property<int>("pentaKills")
                        .HasColumnType("int");

                    b.Property<int>("perfectDragonSoulsTaken")
                        .HasColumnType("int");

                    b.Property<int>("perfectGame")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("physicalDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("pickKillWithAlly")
                        .HasColumnType("int");

                    b.Property<int>("pushPings")
                        .HasColumnType("int");

                    b.Property<int>("quadraKills")
                        .HasColumnType("int");

                    b.Property<int>("quickCleanse")
                        .HasColumnType("int");

                    b.Property<int>("quickFirstTurret")
                        .HasColumnType("int");

                    b.Property<int>("quickSoloKills")
                        .HasColumnType("int");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<int>("retreatPings")
                        .HasColumnType("int");

                    b.Property<int>("riftHerald")
                        .HasColumnType("int");

                    b.Property<int>("riftHeraldTakedowns")
                        .HasColumnType("int");

                    b.Property<bool>("riftHerald_first")
                        .HasColumnType("bit");

                    b.Property<string>("riotIdGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("saveAllyFromDeath")
                        .HasColumnType("int");

                    b.Property<int>("scuttleCrabKills")
                        .HasColumnType("int");

                    b.Property<int>("skillshotsDodged")
                        .HasColumnType("int");

                    b.Property<int>("skillshotsHit")
                        .HasColumnType("int");

                    b.Property<int>("soloBaronKills")
                        .HasColumnType("int");

                    b.Property<int>("soloKills")
                        .HasColumnType("int");

                    b.Property<int>("soloTurretsLategame")
                        .HasColumnType("int");

                    b.Property<int>("spell1Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell2Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell3Casts")
                        .HasColumnType("int");

                    b.Property<int>("spell4Casts")
                        .HasColumnType("int");

                    b.Property<int>("stealthWardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("summoner1Casts")
                        .HasColumnType("int");

                    b.Property<int>("summoner1Id")
                        .HasColumnType("int");

                    b.Property<int>("summoner2Casts")
                        .HasColumnType("int");

                    b.Property<int>("summoner2Id")
                        .HasColumnType("int");

                    b.Property<string>("summonerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("summonerLevel")
                        .HasColumnType("int");

                    b.Property<string>("summonerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("survivedSingleDigitHpCount")
                        .HasColumnType("int");

                    b.Property<int>("survivedThreeImmobilizesInFight")
                        .HasColumnType("int");

                    b.Property<int>("takedownOnFirstTurret")
                        .HasColumnType("int");

                    b.Property<int>("takedowns")
                        .HasColumnType("int");

                    b.Property<int>("takedownsAfterGainingLevelAdvantage")
                        .HasColumnType("int");

                    b.Property<int>("takedownsBeforeJungleMinionSpawn")
                        .HasColumnType("int");

                    b.Property<int>("takedownsFirstXMinutes")
                        .HasColumnType("int");

                    b.Property<int>("takedownsInAlcove")
                        .HasColumnType("int");

                    b.Property<int>("takedownsInEnemyFountain")
                        .HasColumnType("int");

                    b.Property<int>("teamBaronKills")
                        .HasColumnType("int");

                    b.Property<float>("teamDamagePercentage")
                        .HasColumnType("real");

                    b.Property<bool>("teamEarlySurrendered")
                        .HasColumnType("bit");

                    b.Property<int>("teamElderDragonKills")
                        .HasColumnType("int");

                    b.Property<int>("teamRiftHeraldKills")
                        .HasColumnType("int");

                    b.Property<int>("timeCCingOthers")
                        .HasColumnType("int");

                    b.Property<int>("timePlayed")
                        .HasColumnType("int");

                    b.Property<int>("tookLargeDamageSurvived")
                        .HasColumnType("int");

                    b.Property<int>("totalAllyJungleMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageShieldedOnTeammates")
                        .HasColumnType("int");

                    b.Property<int>("totalDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("totalEnemyJungleMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalHeal")
                        .HasColumnType("int");

                    b.Property<int>("totalHealsOnTeammates")
                        .HasColumnType("int");

                    b.Property<int>("totalMinionsKilled")
                        .HasColumnType("int");

                    b.Property<int>("totalTimeCCDealt")
                        .HasColumnType("int");

                    b.Property<int>("totalTimeSpentDead")
                        .HasColumnType("int");

                    b.Property<int>("totalUnitsHealed")
                        .HasColumnType("int");

                    b.Property<int>("tower")
                        .HasColumnType("int");

                    b.Property<bool>("tower_first")
                        .HasColumnType("bit");

                    b.Property<int>("tripleKills")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int>("trueDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("turretKills")
                        .HasColumnType("int");

                    b.Property<int>("turretPlatesTaken")
                        .HasColumnType("int");

                    b.Property<int>("turretTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("turretsLost")
                        .HasColumnType("int");

                    b.Property<int>("turretsTakenWithRiftHerald")
                        .HasColumnType("int");

                    b.Property<int>("twentyMinionsIn3SecondsCount")
                        .HasColumnType("int");

                    b.Property<int>("twoWardsOneSweeperCount")
                        .HasColumnType("int");

                    b.Property<int>("visionClearedPings")
                        .HasColumnType("int");

                    b.Property<int>("visionScore")
                        .HasColumnType("int");

                    b.Property<float>("visionScoreAdvantageLaneOpponent")
                        .HasColumnType("real");

                    b.Property<float>("visionScorePerMinute")
                        .HasColumnType("real");

                    b.Property<int>("visionWardsBoughtInGame")
                        .HasColumnType("int");

                    b.Property<int>("voidMonsterKill")
                        .HasColumnType("int");

                    b.Property<int>("wardTakedowns")
                        .HasColumnType("int");

                    b.Property<int>("wardTakedownsBefore20M")
                        .HasColumnType("int");

                    b.Property<int>("wardsGuarded")
                        .HasColumnType("int");

                    b.Property<int>("wardsKilled")
                        .HasColumnType("int");

                    b.Property<int>("wardsPlaced")
                        .HasColumnType("int");

                    b.Property<bool>("win")
                        .HasColumnType("bit");

                    b.HasKey("matchId", "puuid");

                    b.ToTable("Secondary");
                });

            modelBuilder.Entity("magisterka2.Secondary_averave", b =>
                {
                    b.Property<string>("puuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("HealFromMapSources")
                        .HasColumnType("float");

                    b.Property<double>("InfernalScalePickup")
                        .HasColumnType("float");

                    b.Property<double>("abilityUses")
                        .HasColumnType("float");

                    b.Property<double>("allInPings")
                        .HasColumnType("float");

                    b.Property<double>("alliedJungleMonsterKills")
                        .HasColumnType("float");

                    b.Property<double>("assistMePings")
                        .HasColumnType("float");

                    b.Property<double>("assists")
                        .HasColumnType("float");

                    b.Property<double>("atakhan")
                        .HasColumnType("float");

                    b.Property<double>("atakhan_first")
                        .HasColumnType("float");

                    b.Property<double>("baron")
                        .HasColumnType("float");

                    b.Property<double>("baronBuffGoldAdvantageOverThreshold")
                        .HasColumnType("float");

                    b.Property<double>("baronKills")
                        .HasColumnType("float");

                    b.Property<double>("baronTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("baron_first")
                        .HasColumnType("float");

                    b.Property<double>("blastConeOppositeOpponentCount")
                        .HasColumnType("float");

                    b.Property<double>("bountyGold")
                        .HasColumnType("float");

                    b.Property<double>("bountyLevel")
                        .HasColumnType("float");

                    b.Property<double>("buffsStolen")
                        .HasColumnType("float");

                    b.Property<double>("champion")
                        .HasColumnType("float");

                    b.Property<double>("champion_first")
                        .HasColumnType("float");

                    b.Property<double>("commandPings")
                        .HasColumnType("float");

                    b.Property<double>("consumablesPurchased")
                        .HasColumnType("float");

                    b.Property<double>("controlWardTimeCoverageInRiverOrEnemyHalf")
                        .HasColumnType("float");

                    b.Property<double>("controlWardsPlaced")
                        .HasColumnType("float");

                    b.Property<double>("damageDealtToBuildings")
                        .HasColumnType("float");

                    b.Property<double>("damageDealtToObjectives")
                        .HasColumnType("float");

                    b.Property<double>("damageDealtToTurrets")
                        .HasColumnType("float");

                    b.Property<double>("damagePerMinute")
                        .HasColumnType("float");

                    b.Property<double>("damageSelfMitigated")
                        .HasColumnType("float");

                    b.Property<double>("damageTakenOnTeamPercentage")
                        .HasColumnType("float");

                    b.Property<double>("deaths")
                        .HasColumnType("float");

                    b.Property<double>("deathsByEnemyChamps")
                        .HasColumnType("float");

                    b.Property<double>("detectorWardsPlaced")
                        .HasColumnType("float");

                    b.Property<double>("dodgeSkillShotsSmallWindow")
                        .HasColumnType("float");

                    b.Property<double>("doubleKills")
                        .HasColumnType("float");

                    b.Property<double>("dragon")
                        .HasColumnType("float");

                    b.Property<double>("dragonKills")
                        .HasColumnType("float");

                    b.Property<double>("dragonTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("dragon_first")
                        .HasColumnType("float");

                    b.Property<double>("earliestBaron")
                        .HasColumnType("float");

                    b.Property<double>("earliestDragonTakedown")
                        .HasColumnType("float");

                    b.Property<double>("effectiveHealAndShielding")
                        .HasColumnType("float");

                    b.Property<double>("elderDragonKillsWithOpposingSoul")
                        .HasColumnType("float");

                    b.Property<double>("elderDragonMultikills")
                        .HasColumnType("float");

                    b.Property<double>("eligibleForProgression")
                        .HasColumnType("float");

                    b.Property<double>("enemyChampionImmobilizations")
                        .HasColumnType("float");

                    b.Property<double>("enemyJungleMonsterKills")
                        .HasColumnType("float");

                    b.Property<double>("enemyMissingPings")
                        .HasColumnType("float");

                    b.Property<double>("enemyVisionPings")
                        .HasColumnType("float");

                    b.Property<double>("epicMonsterKillsNearEnemyJungler")
                        .HasColumnType("float");

                    b.Property<double>("epicMonsterKillsWithin30SecondsOfSpawn")
                        .HasColumnType("float");

                    b.Property<double>("epicMonsterSteals")
                        .HasColumnType("float");

                    b.Property<double>("epicMonsterStolenWithoutSmite")
                        .HasColumnType("float");

                    b.Property<double>("fasterSupportQuestCompletion")
                        .HasColumnType("float");

                    b.Property<double>("firstBloodAssist")
                        .HasColumnType("float");

                    b.Property<double>("firstBloodKill")
                        .HasColumnType("float");

                    b.Property<double>("firstTowerAssist")
                        .HasColumnType("float");

                    b.Property<double>("firstTowerKill")
                        .HasColumnType("float");

                    b.Property<double>("firstTurretKilledTime")
                        .HasColumnType("float");

                    b.Property<double>("fullTeamTakedown")
                        .HasColumnType("float");

                    b.Property<double>("gameEndedInEarlySurrender")
                        .HasColumnType("float");

                    b.Property<double>("gameEndedInSurrender")
                        .HasColumnType("float");

                    b.Property<double>("gameLength")
                        .HasColumnType("float");

                    b.Property<double>("getBackPings")
                        .HasColumnType("float");

                    b.Property<double>("getTakedownsInAllLanesEarlyJungleAsLaner")
                        .HasColumnType("float");

                    b.Property<double>("goldEarned")
                        .HasColumnType("float");

                    b.Property<double>("goldPerMinute")
                        .HasColumnType("float");

                    b.Property<double>("goldSpent")
                        .HasColumnType("float");

                    b.Property<double>("highestChampionDamage")
                        .HasColumnType("float");

                    b.Property<double>("highestCrowdControlScore")
                        .HasColumnType("float");

                    b.Property<double>("holdPings")
                        .HasColumnType("float");

                    b.Property<double>("horde")
                        .HasColumnType("float");

                    b.Property<double>("horde_first")
                        .HasColumnType("float");

                    b.Property<double>("immobilizeAndKillWithAlly")
                        .HasColumnType("float");

                    b.Property<string>("individualPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("inhibitor")
                        .HasColumnType("float");

                    b.Property<double>("inhibitorKills")
                        .HasColumnType("float");

                    b.Property<double>("inhibitorTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("inhibitor_first")
                        .HasColumnType("float");

                    b.Property<double>("inhibitorsLost")
                        .HasColumnType("float");

                    b.Property<double>("initialBuffCount")
                        .HasColumnType("float");

                    b.Property<double>("initialCrabCount")
                        .HasColumnType("float");

                    b.Property<double>("itemsPurchased")
                        .HasColumnType("float");

                    b.Property<double>("jungleCsBefore10Minutes")
                        .HasColumnType("float");

                    b.Property<double>("junglerKillsEarlyJungle")
                        .HasColumnType("float");

                    b.Property<double>("junglerTakedownsNearDamagedEpicMonster")
                        .HasColumnType("float");

                    b.Property<double>("kTurretsDestroyedBeforePlatesFall")
                        .HasColumnType("float");

                    b.Property<double>("kda")
                        .HasColumnType("float");

                    b.Property<double>("killAfterHiddenWithAlly")
                        .HasColumnType("float");

                    b.Property<double>("killParticipation")
                        .HasColumnType("float");

                    b.Property<double>("killedChampTookFullTeamDamageSurvived")
                        .HasColumnType("float");

                    b.Property<double>("killingSprees")
                        .HasColumnType("float");

                    b.Property<double>("kills")
                        .HasColumnType("float");

                    b.Property<double>("killsNearEnemyTurret")
                        .HasColumnType("float");

                    b.Property<double>("killsOnLanersEarlyJungleAsJungler")
                        .HasColumnType("float");

                    b.Property<double>("killsOnOtherLanesEarlyJungleAsLaner")
                        .HasColumnType("float");

                    b.Property<double>("killsUnderOwnTurret")
                        .HasColumnType("float");

                    b.Property<double>("killsWithHelpFromEpicMonster")
                        .HasColumnType("float");

                    b.Property<double>("knockEnemyIntoTeamAndKill")
                        .HasColumnType("float");

                    b.Property<double>("landSkillShotsEarlyGame")
                        .HasColumnType("float");

                    b.Property<string>("lane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("laneMinionsFirst10Minutes")
                        .HasColumnType("float");

                    b.Property<double>("laningPhaseGoldExpAdvantage")
                        .HasColumnType("float");

                    b.Property<double>("largestCriticalStrike")
                        .HasColumnType("float");

                    b.Property<double>("largestKillingSpree")
                        .HasColumnType("float");

                    b.Property<double>("largestMultiKill")
                        .HasColumnType("float");

                    b.Property<double>("legendaryCount")
                        .HasColumnType("float");

                    b.Property<double>("longestTimeSpentLiving")
                        .HasColumnType("float");

                    b.Property<double>("magicDamageDealt")
                        .HasColumnType("float");

                    b.Property<double>("magicDamageDealtToChampions")
                        .HasColumnType("float");

                    b.Property<double>("magicDamageTaken")
                        .HasColumnType("float");

                    b.Property<double>("maxCsAdvantageOnLaneOpponent")
                        .HasColumnType("float");

                    b.Property<double>("maxKillDeficit")
                        .HasColumnType("float");

                    b.Property<double>("maxLevelLeadLaneOpponent")
                        .HasColumnType("float");

                    b.Property<double>("moreEnemyJungleThanOpponent")
                        .HasColumnType("float");

                    b.Property<double>("multiKillOneSpell")
                        .HasColumnType("float");

                    b.Property<double>("multiTurretRiftHeraldCount")
                        .HasColumnType("float");

                    b.Property<double>("multikills")
                        .HasColumnType("float");

                    b.Property<double>("multikillsAfterAggressiveFlash")
                        .HasColumnType("float");

                    b.Property<double>("needVisionPings")
                        .HasColumnType("float");

                    b.Property<double>("neutralMinionsKilled")
                        .HasColumnType("float");

                    b.Property<double>("nexusKills")
                        .HasColumnType("float");

                    b.Property<double>("nexusLost")
                        .HasColumnType("float");

                    b.Property<double>("nexusTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("objectivesStolen")
                        .HasColumnType("float");

                    b.Property<double>("objectivesStolenAssists")
                        .HasColumnType("float");

                    b.Property<double>("onMyWayPings")
                        .HasColumnType("float");

                    b.Property<double>("outnumberedKills")
                        .HasColumnType("float");

                    b.Property<double>("outnumberedNexusKill")
                        .HasColumnType("float");

                    b.Property<double>("pentaKills")
                        .HasColumnType("float");

                    b.Property<double>("perfectDragonSoulsTaken")
                        .HasColumnType("float");

                    b.Property<double>("perfectGame")
                        .HasColumnType("float");

                    b.Property<double>("physicalDamageDealt")
                        .HasColumnType("float");

                    b.Property<double>("physicalDamageDealtToChampions")
                        .HasColumnType("float");

                    b.Property<double>("physicalDamageTaken")
                        .HasColumnType("float");

                    b.Property<double>("pickKillWithAlly")
                        .HasColumnType("float");

                    b.Property<double>("pushPings")
                        .HasColumnType("float");

                    b.Property<double>("quadraKills")
                        .HasColumnType("float");

                    b.Property<double>("quickCleanse")
                        .HasColumnType("float");

                    b.Property<double>("quickFirstTurret")
                        .HasColumnType("float");

                    b.Property<double>("quickSoloKills")
                        .HasColumnType("float");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<double>("retreatPings")
                        .HasColumnType("float");

                    b.Property<double>("riftHerald")
                        .HasColumnType("float");

                    b.Property<double>("riftHeraldTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("riftHerald_first")
                        .HasColumnType("float");

                    b.Property<string>("riotIdGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("saveAllyFromDeath")
                        .HasColumnType("float");

                    b.Property<double>("scuttleCrabKills")
                        .HasColumnType("float");

                    b.Property<double>("skillshotsDodged")
                        .HasColumnType("float");

                    b.Property<double>("skillshotsHit")
                        .HasColumnType("float");

                    b.Property<double>("soloBaronKills")
                        .HasColumnType("float");

                    b.Property<double>("soloKills")
                        .HasColumnType("float");

                    b.Property<double>("soloTurretsLategame")
                        .HasColumnType("float");

                    b.Property<double>("spell1Casts")
                        .HasColumnType("float");

                    b.Property<double>("spell2Casts")
                        .HasColumnType("float");

                    b.Property<double>("spell3Casts")
                        .HasColumnType("float");

                    b.Property<double>("spell4Casts")
                        .HasColumnType("float");

                    b.Property<double>("stealthWardsPlaced")
                        .HasColumnType("float");

                    b.Property<double>("summoner1Casts")
                        .HasColumnType("float");

                    b.Property<double>("summoner1Id")
                        .HasColumnType("float");

                    b.Property<double>("summoner2Casts")
                        .HasColumnType("float");

                    b.Property<double>("summoner2Id")
                        .HasColumnType("float");

                    b.Property<string>("summonerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("summonerLevel")
                        .HasColumnType("float");

                    b.Property<string>("summonerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("survivedSingleDigitHpCount")
                        .HasColumnType("float");

                    b.Property<double>("survivedThreeImmobilizesInFight")
                        .HasColumnType("float");

                    b.Property<double>("takedownOnFirstTurret")
                        .HasColumnType("float");

                    b.Property<double>("takedowns")
                        .HasColumnType("float");

                    b.Property<double>("takedownsAfterGainingLevelAdvantage")
                        .HasColumnType("float");

                    b.Property<double>("takedownsBeforeJungleMinionSpawn")
                        .HasColumnType("float");

                    b.Property<double>("takedownsFirstXMinutes")
                        .HasColumnType("float");

                    b.Property<double>("takedownsInAlcove")
                        .HasColumnType("float");

                    b.Property<double>("takedownsInEnemyFountain")
                        .HasColumnType("float");

                    b.Property<double>("teamBaronKills")
                        .HasColumnType("float");

                    b.Property<double>("teamDamagePercentage")
                        .HasColumnType("float");

                    b.Property<double>("teamEarlySurrendered")
                        .HasColumnType("float");

                    b.Property<double>("teamElderDragonKills")
                        .HasColumnType("float");

                    b.Property<double>("teamRiftHeraldKills")
                        .HasColumnType("float");

                    b.Property<double>("timeCCingOthers")
                        .HasColumnType("float");

                    b.Property<double>("timePlayed")
                        .HasColumnType("float");

                    b.Property<double>("tookLargeDamageSurvived")
                        .HasColumnType("float");

                    b.Property<double>("totalAllyJungleMinionsKilled")
                        .HasColumnType("float");

                    b.Property<double>("totalDamageDealt")
                        .HasColumnType("float");

                    b.Property<double>("totalDamageDealtToChampions")
                        .HasColumnType("float");

                    b.Property<double>("totalDamageShieldedOnTeammates")
                        .HasColumnType("float");

                    b.Property<double>("totalDamageTaken")
                        .HasColumnType("float");

                    b.Property<double>("totalEnemyJungleMinionsKilled")
                        .HasColumnType("float");

                    b.Property<double>("totalHeal")
                        .HasColumnType("float");

                    b.Property<double>("totalHealsOnTeammates")
                        .HasColumnType("float");

                    b.Property<double>("totalMinionsKilled")
                        .HasColumnType("float");

                    b.Property<double>("totalTimeCCDealt")
                        .HasColumnType("float");

                    b.Property<double>("totalTimeSpentDead")
                        .HasColumnType("float");

                    b.Property<double>("totalUnitsHealed")
                        .HasColumnType("float");

                    b.Property<double>("tower")
                        .HasColumnType("float");

                    b.Property<double>("tower_first")
                        .HasColumnType("float");

                    b.Property<double>("tripleKills")
                        .HasColumnType("float");

                    b.Property<double>("trueDamageDealt")
                        .HasColumnType("float");

                    b.Property<double>("trueDamageDealtToChampions")
                        .HasColumnType("float");

                    b.Property<double>("trueDamageTaken")
                        .HasColumnType("float");

                    b.Property<double>("turretKills")
                        .HasColumnType("float");

                    b.Property<double>("turretPlatesTaken")
                        .HasColumnType("float");

                    b.Property<double>("turretTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("turretsLost")
                        .HasColumnType("float");

                    b.Property<double>("turretsTakenWithRiftHerald")
                        .HasColumnType("float");

                    b.Property<double>("twentyMinionsIn3SecondsCount")
                        .HasColumnType("float");

                    b.Property<double>("twoWardsOneSweeperCount")
                        .HasColumnType("float");

                    b.Property<double>("visionClearedPings")
                        .HasColumnType("float");

                    b.Property<double>("visionScore")
                        .HasColumnType("float");

                    b.Property<double>("visionScoreAdvantageLaneOpponent")
                        .HasColumnType("float");

                    b.Property<double>("visionScorePerMinute")
                        .HasColumnType("float");

                    b.Property<double>("visionWardsBoughtInGame")
                        .HasColumnType("float");

                    b.Property<double>("voidMonsterKill")
                        .HasColumnType("float");

                    b.Property<double>("wardTakedowns")
                        .HasColumnType("float");

                    b.Property<double>("wardTakedownsBefore20M")
                        .HasColumnType("float");

                    b.Property<double>("wardsGuarded")
                        .HasColumnType("float");

                    b.Property<double>("wardsKilled")
                        .HasColumnType("float");

                    b.Property<double>("wardsPlaced")
                        .HasColumnType("float");

                    b.Property<double>("win")
                        .HasColumnType("float");

                    b.HasKey("puuid");

                    b.ToTable("Secondary_Awerage");
                });
#pragma warning restore 612, 618
        }
    }
}
